tasks:
  - name: espressif
    init: ./init.sh |& tee init.log
    command: . esp/esp-idf/export.sh && cd esp/hello_world && idf.py build

vscode:
  extensions:
    - espressif.esp-idf-extension@1.0.1:CgNK6XBQjTfVZ4DfDrPCMg==
